name: ovo_meet
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.14
  flutter_widget_from_html: ^0.15.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.3
  open_file: ^3.5.9
  pin_code_fields: ^8.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  simple_ripple_animation: ^0.0.9
  url_launcher: ^6.3.1
  flutter_zoom_drawer: ^3.2.0
  persistent_bottom_nav_bar: ^6.2.1
  # Firebase core for Flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.12
  flutter_datetime_picker_plus: ^2.2.0
  geoflutterfire_plus: ^0.0.24
  google_maps_flutter: ^2.6.0
  google_places_flutter: ^2.0.9
  # Stream Chat for real-time messaging
  stream_chat_flutter: ^9.7.0
  stream_chat_flutter_core: ^9.7.0
  stream_chat: ^9.7.0
  rxdart: ^0.28.0

dependency_overrides:
  # Force compatible record package versions
  record: ^6.0.0
  record_linux: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/menu/
    - assets/images/social/
    - assets/images/menu/
    - assets/images/select_interests/
    - assets/images/onboard/
    - assets/animation/
    - assets/fonts/

  fonts:
    - family: "Vogue"
      fonts:
        - asset: assets/fonts/Vogue.ttf
    - family: "dancing"
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: "Inter"
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
